name: wk1
on:
  pull_request:
    branches: [main]
env:
  AZURE_WEBAPP_NAME: AppSmutum
  RESOURCE_GROUP: RG1
  LOAD_TEST_RESOURCE: az2006loadtest  # Replace with actual resource name
  
jobs:
  complete-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      
      - name: dotnet build and publish
        run: |
          dotnet restore FruitAPI/FruitAPI.csproj
          dotnet build FruitAPI/FruitAPI.csproj --configuration Release
          dotnet publish FruitAPI/FruitAPI.csproj -c Release --output ./publish
          cd ./publish && zip -r ../app.zip .
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
        
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      # Changed: Use azure/webapps-deploy@v3 instead of azure/cli
      - name: Deploy to Azure Web App staging slot
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: staging
          package: app.zip
          
      # Changed: Use azure/load-testing@v1 instead of CLI commands
      - name: Run Azure Load Testing
        uses: azure/load-testing@v1
        with:
          loadtestConfigFile: 'test1.yml'
          loadtestResource: ${{ env.LOAD_TEST_RESOURCE }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          env: |
            [
              {
                "name": "HTTPSample.domain",
                "value": "https://${{ env.AZURE_WEBAPP_NAME }}-staging.azurewebsites.net"
              }
            ]
        id: loadtest
            
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: loadTestResults
          path: loadTest/results.zip
          
      - name: Check load test results
        run: |
          if [ "${{ steps.loadtest.outputs.result }}" != "PASSED" ]; then
            echo "Load test failed according to test1.yml criteria"
            exit 1
          fi
          echo "Load test passed according to test1.yml criteria"
