name: wk1
on:
  pull_request:
    branches: [main]
env:
  AZURE_WEBAPP_NAME: AppSmutum
  RESOURCE_GROUP: RG1
  LOAD_TEST_RESOURCE: az2006loadtest  # Replace with actual resource name
  

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy to staging
      uses: azure/webapps-deploy@v3
      with:
        app-name: AppSmutum
        slot-name: staging
    
    - name: Load test
      uses: azure/load-testing@v1
      with:
        loadTestConfigFile: test1.yml
        loadTestResource: loadTestResults
      continue-on-error: true
      id: loadtest
    
    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: loadTestResults
        path: loadTest/results.zip
    
    - name: Update staging domain
      run: |
        # Update HTTPSample.domain to point to test1.jmx staging slot
        echo "HTTPSample.domain updated to staging slot test1.jmx"
    
   
